### ISSUE TITLE
未找到服务：reminder

### ISSUE THREAD

**Issue by AndoKaguya** [assassingyk/reminder#1]
大佬，你好，想请教一下
将reminder解压到/hoshino/modules/reminder中，
在__bot__.py里配置启用 reminder，然后启动bot，
bot服务列表中未找到reminder，使用相关设置指令也没有响应，
可否指点一下具体的操作姿势呢？

**Comment by assassingyk** [comment]
听起来大概是你启动的时候加载插件就失败了，建议重新看看启动时有没有报错信息
