### ISSUE TITLE
cron表达式解析报错时，依然会将cron表达式写入到数据，并且调用命令无法删除掉

### ISSUE THREAD

**Issue by howrain** [assassingyk/reminder#2]
![image](https://user-images.githubusercontent.com/29175296/138799006-e25e35d2-9a6c-4040-8003-d3ec49cb3b8c.png)
![image](https://user-images.githubusercontent.com/29175296/138799091-0fcd8f04-b50f-440e-b08c-628d7f5b5401.png)
![image](https://user-images.githubusercontent.com/29175296/138799121-2b413873-dfc2-49ab-bef1-8c2d6fee11da.png)

**Comment by assassingyk** [comment]
理论上?应该是可以放在day_of_week里的……可能是nonebot.scheduler自己解析的条件不太一样，可以调整下checkcron那个函数提前滤掉参数不合法的cron表达式……
![image](https://user-images.githubusercontent.com/55473115/138812916-eb8c8eeb-0731-41ee-81a4-1223fade340c.png)

写入和删除这个问题可以调整下删除配置和删除任务的逻辑顺序，这个应该还好。已经写进去的手动删配置文件也行（）

**Comment by assassingyk** [comment]
重新想了想，手动判断corn合不合法实在太麻烦了，还是直接执行一遍add_job好了……
现在应该是如果cron解析报错就直接跳出不会再走写入json的过程了

**Comment by howrain** [comment]
> 重新想了想，手动判断corn合不合法实在太麻烦了，还是直接执行一遍add_job好了…… 现在应该是如果cron解析报错就直接跳出不会再走写入json的过程了

是的，我想也是 报错直接不写入就行了
