### ISSUE TITLE
时区可能引发的BUG。

### ISSUE THREAD

**Issue by mikuyourworld** [assassingyk/reminder#3]
我的机器人是挂在GMT+9的电脑上的。
设置了一个晚上10点的定时提醒。。但是不管是gmt+8的10点还是gmt+9的10点都没有触发。
在log里有记录 但是群消息没有发出来。

log如下
Run time of job "send_group_reminder (trigger: cron[month='*', day='*', day_of_week='*', hour='22', minute='0'], next run at: 2022-04-08 22:00:00 CST)" was missed by 0:00:01.453868

**Comment by assassingyk** [comment]
有log那应该是触发了的，没发出来更可能是风控的锅。建议看下go的log看看有没有风控，或者如果提醒内容是图片建议换成文字再试下

**Comment by mikuyourworld** [comment]
他只有这个log没有那个推送失败log。
不过现在正常了。我设置了一个10点01分的。正常推送2天了。说不定是不能设置00分？

**Comment by assassingyk** [comment]
按说和整点应该没关系，没报错可能是go端不报错的那种隐性风控，如果你推送的内容带图片或者带链接什么的就很有可能。

建议用控制变量法做下实验，比如相同内容不同时间推送和相同时间推送不同内容什么的（）

**Comment by mikuyourworld** [comment]
好的，谢谢解答。
暂时推送的都是文字内容，没有图片或者链接。
我再测试测试。
